import { Inter } from "next/font/google";
import { Helmet } from "react-helmet";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <Helmet>
        <link
          rel="preload"
          href="https://brainb.netlify.app/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Helmet>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export default RootLayout